export interface IBradescoSimulationData {
  id?: bigint
  created_at?: Date
  tipoSistemaAmortizador?: string
  valorFinanciamento?: number
  prazoFinanciamento?: bigint
  valorTaxaJurosEfetivoAno?: number
  valorPrimeiraPrestacaoSemSeguroTac?: number
  valorPrimeiraPrestacaoComSeguroTac?: number
  valorUltimaPrestacao?: number
  valorRendaInformada?: number
  valorRendaLiquidaMinimaExigida?: number
  valorCeshAno?: number
  valorCetAno?: number
  valorDevidoAtoContratacao?: number
  percentualDevidoAtoContratacao?: number
  valorLiberadoCliente?: number
  percentualValorLiberadoCliente?: number
  percentualTag?: number
  valorSeguro?: number
  valorTaxaAdministracaoMensal?: number
  indicadorFgts?: boolean
  dataSimulacao?: string
  descricaoGarantiaOperacao?: string
  codigoCarteira?: string
  descricaoCarteira?: string
  valorImovel?: number
  valorTotalDespesasFinanceiras?: number
  valorTotalFinanciamento?: number
  valorIof?: number
  indexador?: string
  valorRdm?: number
  valorTaxaNominal?: number
  valorTag?: number
  cpf?: string
  id_usuario?: string
  nome?: string
}
