export { IBankApiService } from './BankApiService.interface'
export { ICreditSimulationRepository } from './CreditSimulationRepository.interface'
export { IBradescoSimulationData } from './BradescoSimulationData.interface'
export { IBradescoSimulationRepository } from './BradescoSimulationRepository.interface'
export { IItauSimulationData } from './ItauSimulationData.interface'
export { IItauSimulationRepository } from './ItauSimulationRepository.interface'
export { ISantanderSimulationData } from './SantanderSimulationData.interface'
export { ISantanderSimulationRepository } from './SantanderSimulationRepository.interface'
export { IBankProposalApiService } from './BankProposalApiService.interface'
export * from './ItauProposalRepository.interface'
export * from './InterProposalRepository.interface'
export * from './ProposalClientRepository.interface'
