export interface ISantanderSimulationData {
  id?: bigint
  created_at?: Date
  id_santander?: string | null
  id_santander_decript?: string | null
  produto?: string | null
  valor_imovel?: number | null
  fgts?: number | null
  valor_solicitado?: number | null
  prazo_anos?: bigint | null
  prazo_meses?: bigint | null
  valor_minimo_solicitado?: number | null
  valor_maximo_solicitado?: number | null
  valor_entrada?: number | null
  valor_custas?: number | null
  valor_iof?: number | null
  valor_financiamento_custas?: number | null
  index_tr?: string | null
  tipo_carteira?: string | null
  campanha?: string | null
  key_campanha?: string | null
  segmento?: string | null
  key_segmento?: string | null
  relacionamento_banco?: string | null
  key_relacionamento_banco?: string | null
  seguro?: string | null
  key_seguro?: string | null
  amortizacao?: string | null
  key_amortizacao?: string | null
  tipo_pagamento?: string | null
  key_tipo_pagamento?: string | null
  tipo_simulacao?: string | null
  taxa_juros_anual?: number | null
  taxa_juros_mensal?: number | null
  primeira_parcela?: number | null
  ultima_parcela?: number | null
  cet?: number | null
  cesh?: number | null
  nome?: string | null
  tipo_imovel?: string | null
  cpf?: string | null
  celular?: string | null
  renda?: number | null
  dt_nascimento?: string | null
  id_usuario?: string | null
}
