export interface ISantanderProposalDetails {
  id?: bigint | null
  created_at?: Date | null
  id_proposta?: string | null
  id_simulacao?: string | null
  id_cliente?: string | null
  produto?: string | null
  id_produto?: bigint | null
  valor_imovel?: number | null
  valor_fgts?: number | null
  prazo_anos?: bigint | null
  prazo_meses?: bigint | null
  valor_financiamento_minimo?: number | null
  valor_financiado_maximo?: number | null
  valor_entrada?: number | null
  valor_despesas?: number | null
  valor_iof?: number | null
  valuation_fee_amount?: number | null
  valor_financiamento_despesas?: number | null
  indexador_tr?: string | null
  tipo_carteira?: string | null
  campanha?: string | null
  id_campanha?: string | null
  segmento?: string | null
  id_segmento?: string | null
  oferta_relacionamento?: string | null
  id_oferta_relacionamento?: string | null
  seguro?: string | null
  id_seguro?: string | null
  tipo_amortizacao?: string | null
  chave_tipo_amortizacao?: string | null
  tipo_pagamento?: string | null
  chave_tipo_pagamento?: string | null
  tipo_simulacao_calculada?: string | null
  valor_juros_anual?: number | null
  valor_juros_mensal?: number | null
  valor_primeira_parcela?: number | null
  valor_ultima_parcela?: number | null
  valor_cet?: number | null
  valor_cesh?: number | null
  situacao?: string | null
  ltv?: string | null
  valor_financiado?: number | null
  id_cliente_most?: bigint | null
  id_status_most?: bigint | null
  id_situacao_most?: bigint | null
  id_substatus_most?: bigint | null
  status_global?: string | null
  status_simulation?: string | null
  status_creditAnalysis?: string | null
  status_informationRegister?: string | null
  status_documentSubmission?: string | null
  status_inspection?: string | null
  status_documentAnalysis?: string | null
  status_currentAccount?: string | null
  status_interveningPayer?: string | null
  status_dataAndValueVerification?: string | null
  status_fgts?: string | null
  status_printingAndSignature?: string | null
  status_signatureCheck?: string | null
  status_contractSubmission?: string | null
  status_releaseOfFunds?: string | null
  taxa_juros_percent?: number | null
  total_documentos?: bigint | null
  proposta_copiada?: boolean | null
  id_cliente_incorporador?: bigint | null
}
