export interface BankResponseSimulation {
  simulationId: string
  bankName: string
  financingValue: number
  installments: number
  firstInstallment: number
  lastInstallment: number
  interestRate: number
  cet: number
  propertyValue: number
  downPayment: number
  amortizationType: string
  ltv: number
  uuidUser?: string

  bankSpecificData?: {
    santander?: {
      id_santander_decript?: string
      produto?: string
      fgts?: number
      prazo_anos?: number
      valor_minimo_solicitado?: number
      valor_maximo_solicitado?: number
      valor_custas?: number
      valor_iof?: number
      valor_financiamento_custas?: number
      index_tr?: string
      tipo_carteira?: string
      campanha?: string
      key_campanha?: string
      segmento?: string
      key_segmento?: string
      relacionamento_banco?: string
      key_relacionamento_banco?: string
      seguro?: string
      key_seguro?: string
      amortizacao?: string
      key_amortizacao?: string
      tipo_pagamento?: string
      key_tipo_pagamento?: string
      tipo_simulacao?: string
      taxa_juros_mensal?: number
      primeira_parcela?: number
      ultima_parcela?: number
      cet?: number
      cesh?: number
      nome?: string
      tipo_imovel?: string
      cpf?: string
      celular?: string
      renda?: number
      dt_nascimento?: string
      id_usuario?: string
    }
    bradesco?: {
      tipo_sistema_amortizador?: string
      valor_renda_informada?: number
      valor_renda_minima_exigida?: number
      valor_cesh_ano?: number
      valor_devido_ato_contratacao?: number
      valor_liberado_cliente?: number
      indicador_fgts?: boolean
      codigo_carteira?: string
      descricao_carteira?: string
      valor_iof?: number
      indexador?: string
    }
    inter?: {
      produto?: string
      valorTotal?: number
      totalCet?: number
      totalCesh?: number
      despesas?: number
      despesasRegistro?: number
      despesasAvaliacao?: number
      percentualIof?: number
      percentualCesh?: number
      urlEvolucaoTeorica: string
      rendaSugerida?: number
      parcelas?: Array<{
        noParcela: number
        valor: number
        valorJuros: number
        valorAmortizacao: number
        balancoDebito: number
        valorIof: number
        valorIofNormal: number
        valorIofAdicional: number
        valorSeguro: number
        valorMip: number
        valorDfi: number
        taxaImpostoAdministrativo: number
        pagarAte: string
      }>
    }
  }
}
