export interface Performance {
  id: bigint
  created_at: string
  cpf_cnpj: bigint
  id_cliente: bigint
  nome_cliente: string
  estado_civil: string
  consultor: string
  status: string
  situacao: string
  banco: string
  valor: number
  nacionalidade: string
  tipo_imovel: string
  sexo: string
  tipo_contato: string
  rg: string
  tipo_endereco: string
  tipo_renda: string
  tipo_amortizacao: string
  tipo_taxa_financiamento: string
  UF_proponente: string
  CEP: string
  valor_entrada: number
  prazo: number
  municipio_imovel: string
  FGTS: boolean
  nr_pis: string
  UF_imovel: string
  tipo_carteira: string
  seguradora: string
  ITBI: boolean
  percent_itbi: string
  vlr_itbi: number
  id_incorporadora: bigint
  id_empreedimento: bigint
  id_bloco: bigint
  id_unidade: bigint
  dt_nasc: string
  nome_mae: string
  orgao_expedidor: string
  uf_rg: string
  data_emissao_rg: string
  data_cadastro: string
  nr_contato: string
  email: string
  endereco: string
  numero_endereco: string
  bairro_endereco: string
  complemento_endereco: string
  cidade_endereco: string
  profissao: string
  regime_trabalho: string
  cnpj_empresa_cliente: string
  nome_empresa: string
  dados_bancarios: string
  data_admissao: string
  outras_rendas: string
  vlr_renda_mensal: number
  estado_civil_cliente: string
  regime_casamento: string
  segundo_proponente: boolean
  uniao_estavel: boolean
  id_segundo_proponente: number
  id_terceiro_proponente: number
  terceiro_proponente: boolean
  cpf_cliente: string
  id_consultor: bigint
  id_lider: number
  parceiro: string
  valor_imovel: number
  credito_aprovado: number
  taxa_juros: number
  vlr_solicitado: number
  vlr_fgts: number
  id_profissao: bigint
  tipo_documento: string
  cargo: string
  tipo_residencia: string
  agencia: string
  conta: string
  digitoConta: string
  codigoCategoriaProfissao: string
  percent_itbi_number: number
  id_itau: string
  id_santander: string
  id_bradesco: string
  id_cef: string
  id_proposta: string
  gerente: string
  ltv: number
}
